/**
 * okena.ts — the native ↔ TypeScript binding contract.
 *
 * ┌───────────────────────────────────────────────────────────────────────┐
 * │ THIS IS A SCAFFOLD / SPEC, NOT THE REAL BINDING.                        │
 * │                                                                         │
 * │ The real implementation is GENERATED by `uniffi-bindgen-react-native`   │
 * │ (`ubrn`) from the sibling Rust crate `crates/okena-mobile-ffi` (the     │
 * │ uniffi-annotated rework of `mobile/native`). See ../../README.md.       │
 * │                                                                         │
 * │ This file declares the agreed-upon TypeScript shape of that generated   │
 * │ module: the `OkenaNative` interface plus all the record/enum types.     │
 * │ Both sides — the Rust `#[uniffi::export]` signatures and this contract  │
 * │ — must stay in sync. When `ubrn` is wired up, the generated package's   │
 * │ exported functions should satisfy `OkenaNative` structurally (this file │
 * │ becomes the typed re-export / shim over the generated module).          │
 * └───────────────────────────────────────────────────────────────────────┘
 *
 * Signature source of truth: `crates/okena-mobile-ffi/src/lib.rs` (the
 * `#[uniffi::export]` surface).
 *
 * Sync vs. async mapping (mirrors the Rust `#[frb(sync)]` / `async fn` split,
 * which `ubrn` maps to synchronous JSI host functions vs. JS Promises):
 *   - SYNC  : cheap getters on the render hot path
 *             (getVisibleCells, getVisibleCellsPacked, getCursor, isDirty,
 *              connectionStatus, getScrollInfo, selection getters, resize*).
 *   - ASYNC : anything that crosses the wire / awaits a server response
 *             (pair, sendText, sendSpecialKey, all *_action / git / service /
 *              project / layout calls, readContent).
 */

// ─────────────────────────────────────────────────────────────────────────
// Scalar / id aliases (documentation only — all are `string`/`number` at runtime)
// ─────────────────────────────────────────────────────────────────────────

/** Opaque connection id returned by `connect`. */
export type ConnId = string;
/** Opaque terminal id (from layout / state). */
export type TerminalId = string;
/** Opaque project id. */
export type ProjectId = string;
/** Opaque folder id. */
export type FolderId = string;
/** Opaque space id. `"default"` is the space every profile has. */
export type SpaceId = string;

// ─────────────────────────────────────────────────────────────────────────
// Enums  (uniffi enums → TS string-union; ubrn emits string-tagged values)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Connection status — mirrors the FFI `ConnectionStatus` enum in
 * `api/connection.rs` (the simplified mobile variant; `Reconnecting` is
 * collapsed into `Connecting` Rust-side).
 *
 * `Error` carries a message, so this is a discriminated union rather than a
 * bare string-union.
 */
export type ConnectionStatus =
  | { kind: 'disconnected' }
  | { kind: 'connecting' }
  | { kind: 'connected' }
  | { kind: 'pairing' }
  | { kind: 'error'; message: string };

/** Cursor shape — mirrors FFI `CursorShape` (`api/terminal.rs`). */
export type CursorShape = 'block' | 'underline' | 'beam';

/**
 * Named special keys the remote API accepts, mirroring
 * `okena_core::keys::SpecialKey`. `sendSpecialKey` takes one of these
 * (serialized to the same JSON variant name Rust expects).
 */
export type SpecialKey =
  | 'Enter'
  | 'Escape'
  | 'Backspace'
  | 'Delete'
  | 'CtrlC'
  | 'CtrlD'
  | 'CtrlZ'
  | 'Tab'
  | 'ArrowUp'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'Home'
  | 'End'
  | 'PageUp'
  | 'PageDown';

/** Diff mode for the git diff / file-contents calls. */
export type DiffMode = 'working_tree' | 'staged';

/** Split direction for `splitTerminal`. */
export type SplitDirection = 'horizontal' | 'vertical';

// ─────────────────────────────────────────────────────────────────────────
// Records (uniffi records → TS interfaces)
// ─────────────────────────────────────────────────────────────────────────

/**
 * A single rendered terminal cell — mirrors FFI `CellData` (`api/terminal.rs`).
 *
 * NOTE: For the render hot path prefer `getVisibleCellsPacked` (see below) +
 * the `decodeCells` reader in `./cells`, which avoids marshalling thousands of
 * these objects across JSI per frame (Decision C in RN_MIGRATION.md §2).
 */
export interface CellData {
  /** The grapheme in this cell (`" "` for blank). */
  character: string;
  /** Foreground color, ARGB packed: `0xAARRGGBB`. */
  fg: number;
  /** Background color, ARGB packed: `0xAARRGGBB`. */
  bg: number;
  /** Style flags bitmask: bold|italic|underline|strikethrough|inverse|dim. See ./cells. */
  flags: number;
}

/** Cursor state — mirrors FFI `CursorState` (`api/terminal.rs`). */
export interface CursorState {
  /** 0-based column. */
  col: number;
  /** 0-based visual row. */
  row: number;
  shape: CursorShape;
  visible: boolean;
}

/** Scroll info — mirrors FFI `ScrollInfo` (`api/terminal.rs`). */
export interface ScrollInfo {
  /** Total lines in the scrollback + screen. */
  totalLines: number;
  /** Number of visible (on-screen) lines. */
  visibleLines: number;
  /** Distance scrolled back from the bottom; 0 == pinned to bottom. */
  displayOffset: number;
}

/**
 * Selection bounds in buffer coordinates — mirrors FFI `SelectionBounds`
 * (`api/terminal.rs`). Rows are `i32` Rust-side (can be negative in scrollback),
 * cols are `u16`.
 */
export interface SelectionBounds {
  startCol: number;
  /** Buffer row; may be negative (scrollback above the screen). */
  startRow: number;
  endCol: number;
  /** Buffer row; may be negative. */
  endRow: number;
}

/** Service info — mirrors FFI `ServiceInfo` (`api/state.rs`). */
export interface ServiceInfo {
  name: string;
  status: string;
  /** Terminal hosting the service, if running. */
  terminalId?: string;
  ports: number[];
  exitCode?: number;
  kind: string;
  isExtra: boolean;
}

/** Project info — mirrors FFI `ProjectInfo` (`api/state.rs`). */
export interface ProjectInfo {
  id: ProjectId;
  name: string;
  path: string;
  showInOverview: boolean;
  terminalIds: TerminalId[];
  /** Map terminalId → display name. */
  terminalNames: Record<TerminalId, string>;
  gitBranch?: string;
  gitLinesAdded: number;
  gitLinesRemoved: number;
  services: ServiceInfo[];
  /** Lowercased folder color name (e.g. `"blue"`). */
  folderColor: string;
}

/** Folder info — mirrors FFI `FolderInfo` (`api/state.rs`). */
export interface FolderInfo {
  id: FolderId;
  name: string;
  projectIds: ProjectId[];
  /** Lowercased folder color name. */
  folderColor: string;
}

/** Fullscreen terminal info — mirrors FFI `FullscreenInfo` (`api/state.rs`). */
export interface FullscreenInfo {
  projectId: ProjectId;
  terminalId: TerminalId;
}

/**
 * One space — mirrors FFI `SpaceInfo` (`api/state.rs`).
 *
 * A space is a separate set of projects, agents, tasks and roots inside one
 * profile. Not a "workspace": okena already uses that word for the one set of
 * projects and layouts saved per profile.
 */
export interface SpaceInfo {
  id: SpaceId;
  name: string;
  /** One of this space's agents is waiting on you. Marks its dot from anywhere. */
  agentWaiting: boolean;
}

// ─────────────────────────────────────────────────────────────────────────
// The binding contract
// ─────────────────────────────────────────────────────────────────────────

/**
 * The full native surface — one method per exported Rust FFI function.
 *
 * Naming: Rust `snake_case` fns map to camelCase here, which is also what
 * `ubrn` emits for the generated JS bindings. `connId`/`terminalId`/etc. are
 * always passed positionally (uniffi has no keyword args, unlike `frb`).
 */
export interface OkenaNative {
  // ── connection.rs ──────────────────────────────────────────────────────

  /** One-time startup init (sets up the ConnectionManager singleton). */
  initApp(): void;

  /**
   * Open a connection to a remote server, returning its conn id. If a saved
   * token is supplied, pairing is skipped. (sync — just registers + kicks off
   * the connect; status is then polled via `connectionStatus`.)
   */
  connect(
    host: string,
    port: number,
    savedToken: string | undefined,
    tls: boolean,
    pinnedCertFingerprint: string | undefined,
  ): ConnId;

  /** Current auth token for a connection, if paired. */
  getToken(connId: ConnId): string | undefined;

  /**
   * The server certificate fingerprint this connection is pinned to, if any.
   * `undefined` means no TLS identity was established, so a token obtained here
   * was accepted trust-on-first-use and must not be treated as pinned. Only
   * meaningful when {@link canReportCertFingerprint} is true.
   */
  getCertFingerprint(connId: ConnId): string | undefined;

  /**
   * Whether this binding build implements {@link getCertFingerprint}.
   *
   * Adapter-provided, NOT a Rust export: `src/generated` is gitignored, so a
   * tree built before `get_cert_fingerprint` existed keeps working with an
   * older binding. Callers must not treat a missing pin as "no pin" — that
   * would force a re-pair on every launch without buying any protection.
   */
  canReportCertFingerprint(): boolean;

  /** Pair with the server using a pairing code (async — awaits the server). */
  pair(connId: ConnId, code: string): Promise<void>;

  /** Close the WS and clean up. */
  disconnect(connId: ConnId): void;

  /** Current connection status. */
  connectionStatus(connId: ConnId): ConnectionStatus;

  /**
   * Seconds since the last WS activity (terminal output). Returns a large
   * value if the connection doesn't exist. Used for the staleness indicator.
   */
  secondsSinceActivity(connId: ConnId): number;

  // ── terminal.rs ────────────────────────────────────────────────────────

  /**
   * Visible grid as one record per cell. Convenient for non-hot callers; for
   * the renderer use `getVisibleCellsPacked` instead.
   */
  getVisibleCells(connId: ConnId, terminalId: TerminalId): CellData[];

  /**
   * Visible grid as a packed little-endian binary buffer — the render hot path
   * (Decision C). Layout: `cols:u16, rows:u16` header, then `cols*rows` cells
   * of 13 bytes each (`codepoint:u32, fg:u32, bg:u32, flags:u8`). Decode with
   * `decodeCells` from `./cells`.
   *
   * Implemented Rust-side as `get_visible_cells_packed` in
   * `crates/okena-mobile-ffi/src/lib.rs`; the byte format here is the contract.
   */
  getVisibleCellsPacked(connId: ConnId, terminalId: TerminalId): ArrayBuffer;

  /** Current cursor state. */
  getCursor(connId: ConnId, terminalId: TerminalId): CursorState;

  /** Scroll the display: positive = up (into scrollback), negative = down. */
  scroll(connId: ConnId, terminalId: TerminalId, delta: number): void;

  /** Total/visible line counts and the current display offset. */
  getScrollInfo(connId: ConnId, terminalId: TerminalId): ScrollInfo;

  /** Begin a character-level selection at the given cell. */
  startSelection(connId: ConnId, terminalId: TerminalId, col: number, row: number): void;

  /** Begin a word (semantic) selection at the given cell. */
  startWordSelection(connId: ConnId, terminalId: TerminalId, col: number, row: number): void;

  /** Extend the active selection to the given cell. */
  updateSelection(connId: ConnId, terminalId: TerminalId, col: number, row: number): void;

  /** Clear the active selection. */
  clearSelection(connId: ConnId, terminalId: TerminalId): void;

  /** The currently selected text, if any. */
  getSelectedText(connId: ConnId, terminalId: TerminalId): string | undefined;

  /** Selection bounds for rendering the highlight overlay. */
  getSelectionBounds(connId: ConnId, terminalId: TerminalId): SelectionBounds | undefined;

  /** Send raw text input (async — goes over the WS). */
  sendText(connId: ConnId, terminalId: TerminalId, text: string): Promise<void>;

  /** Resize the terminal locally AND tell the server (async semantics). */
  resizeTerminal(connId: ConnId, terminalId: TerminalId, cols: number, rows: number): void;

  /**
   * Resize ONLY the local alacritty grid — does not notify the server. Used to
   * adapt the mobile viewport to the server's size without round-tripping.
   */
  resizeLocal(connId: ConnId, terminalId: TerminalId, cols: number, rows: number): void;

  // ── state.rs ───────────────────────────────────────────────────────────

  /**
   * The active space's projects from the cached remote state.
   *
   * The daemon's snapshot carries every space's; the Rust side filters, so a
   * project in another space never reaches this layer.
   */
  getProjects(connId: ConnId): ProjectInfo[];

  /** The server's focused project id, if any. */
  getFocusedProjectId(connId: ConnId): ProjectId | undefined;

  /** The active space's folders from the cached remote state. */
  getFolders(connId: ConnId): FolderInfo[];

  /**
   * The spaces the connected daemon holds, in selector order, Default first.
   * Empty from a daemon that predates spaces.
   */
  getSpaces(connId: ConnId): SpaceInfo[];

  /** Which space is showing — what the selector highlights. */
  getActiveSpace(connId: ConnId): SpaceId;

  /**
   * Switch to a space. The daemon owns which one is showing (one per profile),
   * so this asks and the next poll brings the answer back — which is also how
   * a switch made on the desktop reaches the phone.
   */
  activateSpace(connId: ConnId, spaceId: SpaceId): Promise<void>;

  /** The server's project ordering. */
  getProjectOrder(connId: ConnId): ProjectId[];

  /** The fullscreen terminal, if one is active. */
  getFullscreenTerminal(connId: ConnId): FullscreenInfo | undefined;

  /** Layout tree for a project, serialized as JSON (`ApiLayoutNode`). */
  getProjectLayoutJson(connId: ConnId, projectId: ProjectId): string | undefined;

  /** Whether a terminal has unread output since the last cell fetch. */
  isDirty(connId: ConnId, terminalId: TerminalId): boolean;

  /** Send a named special key (async — goes over the WS). */
  sendSpecialKey(connId: ConnId, terminalId: TerminalId, key: SpecialKey): Promise<void>;

  /** Flat list of every terminal id across all projects. */
  getAllTerminalIds(connId: ConnId): TerminalId[];

  // ── terminal actions (state.rs, async) ───────────────────────────────────

  createTerminal(connId: ConnId, projectId: ProjectId): Promise<void>;
  closeTerminal(connId: ConnId, projectId: ProjectId, terminalId: TerminalId): Promise<void>;
  closeTerminals(connId: ConnId, projectId: ProjectId, terminalIds: TerminalId[]): Promise<void>;
  renameTerminal(
    connId: ConnId,
    projectId: ProjectId,
    terminalId: TerminalId,
    name: string,
  ): Promise<void>;
  focusTerminal(connId: ConnId, projectId: ProjectId, terminalId: TerminalId): Promise<void>;
  toggleMinimized(connId: ConnId, projectId: ProjectId, terminalId: TerminalId): Promise<void>;
  /** Set or clear (pass `undefined`) the fullscreen terminal. */
  setFullscreen(
    connId: ConnId,
    projectId: ProjectId,
    terminalId: TerminalId | undefined,
  ): Promise<void>;
  splitTerminal(
    connId: ConnId,
    projectId: ProjectId,
    path: number[],
    direction: SplitDirection,
  ): Promise<void>;
  /** Run a command and auto-press Enter. */
  runCommand(connId: ConnId, terminalId: TerminalId, command: string): Promise<void>;
  /** Read full terminal content as text (awaits a server response). */
  readContent(connId: ConnId, terminalId: TerminalId): Promise<string>;

  // ── git actions (state.rs, async — return JSON strings) ──────────────────

  gitStatus(connId: ConnId, projectId: ProjectId): Promise<string>;
  gitDiffSummary(connId: ConnId, projectId: ProjectId): Promise<string>;
  gitDiff(connId: ConnId, projectId: ProjectId, mode: DiffMode): Promise<string>;
  gitBranches(connId: ConnId, projectId: ProjectId): Promise<string>;
  gitFileContents(
    connId: ConnId,
    projectId: ProjectId,
    filePath: string,
    mode: DiffMode,
  ): Promise<string>;

  // ── service actions (state.rs, async) ────────────────────────────────────

  startService(connId: ConnId, projectId: ProjectId, serviceName: string): Promise<void>;
  stopService(connId: ConnId, projectId: ProjectId, serviceName: string): Promise<void>;
  restartService(connId: ConnId, projectId: ProjectId, serviceName: string): Promise<void>;
  startAllServices(connId: ConnId, projectId: ProjectId): Promise<void>;
  stopAllServices(connId: ConnId, projectId: ProjectId): Promise<void>;
  reloadServices(connId: ConnId, projectId: ProjectId): Promise<void>;

  // ── project management (state.rs, async) ─────────────────────────────────

  addProject(connId: ConnId, name: string, path: string): Promise<void>;
  setProjectColor(connId: ConnId, projectId: ProjectId, color: string): Promise<void>;
  setFolderColor(connId: ConnId, folderId: FolderId, color: string): Promise<void>;
  reorderProjectInFolder(
    connId: ConnId,
    folderId: FolderId,
    projectId: ProjectId,
    newIndex: number,
  ): Promise<void>;

  // ── layout actions (state.rs, async) ─────────────────────────────────────

  updateSplitSizes(
    connId: ConnId,
    projectId: ProjectId,
    path: number[],
    sizes: number[],
  ): Promise<void>;
  addTab(connId: ConnId, projectId: ProjectId, path: number[], inGroup: boolean): Promise<void>;
  setActiveTab(connId: ConnId, projectId: ProjectId, path: number[], index: number): Promise<void>;
  moveTab(
    connId: ConnId,
    projectId: ProjectId,
    path: number[],
    fromIndex: number,
    toIndex: number,
  ): Promise<void>;
  moveTerminalToTabGroup(
    connId: ConnId,
    projectId: ProjectId,
    terminalId: TerminalId,
    targetPath: number[],
    position: number | undefined,
    targetProjectId: ProjectId | undefined,
  ): Promise<void>;
  movePaneTo(
    connId: ConnId,
    projectId: ProjectId,
    terminalId: TerminalId,
    targetProjectId: ProjectId,
    targetTerminalId: TerminalId,
    zone: string,
  ): Promise<void>;
}

/**
 * Resolve the real native module generated by `ubrn` into `src/generated`
 * (see `ubrn.config.yaml`). The lookup is a synchronous Metro `require` — the
 * render hot path calls the native getters synchronously, so a dynamic
 * `import()` (async) is not an option.
 *
 * The require is lazy (inside the function, not a top-level import) so that:
 *   - this typed contract and the presentational components compile/bundle
 *     before `npm run ubrn:*` has produced the module, and
 *   - tests / off-device code that inject a mock `OkenaNative` (via
 *     `configureConnectionStore` / `configureWorkspaceStore` / the `native`
 *     prop) never hit this path.
 *
 * Until the module is generated, the `require` throws and we rethrow with a
 * pointer to the generation step (see mobile/rn/README.md).
 */
/**
 * ubrn → app-contract adapters.
 *
 * ubrn 0.31 represents uniffi types in a few shapes that differ from the
 * hand-written contract above, so the boundary (`getOkenaNative`) translates:
 *   - Data-carrying enums → tagged class instances with a PascalCase `.tag`
 *     (`{ tag: 'Connected' }`; payload under `.inner`, e.g. Error →
 *     `.inner.message`). App wants `{ kind: 'lowercase' }`. → `ConnectionStatus`.
 *   - Fieldless enums → a numeric TS enum (`CursorShape.Block === 0`). App wants
 *     the lowercase string. → `getCursor().shape`.
 *   - Map-typed record fields → a JS `Map`. App indexes them as plain objects.
 *     → `ProjectInfo.terminalNames`.
 * Plain-string enums (split direction, diff mode) and all other record fields
 * already match (camelCase), so they pass through untouched.
 */
function toConnectionStatus(s: {tag?: string; inner?: {message?: string}}): ConnectionStatus {
  switch (s?.tag) {
    case 'Disconnected':
      return {kind: 'disconnected'};
    case 'Connecting':
      return {kind: 'connecting'};
    case 'Connected':
      return {kind: 'connected'};
    case 'Pairing':
      return {kind: 'pairing'};
    case 'Error':
      return {kind: 'error', message: s.inner?.message ?? 'Unknown error'};
    default:
      return {kind: 'disconnected'};
  }
}

// Generated `CursorShape` is a numeric enum (Block=0, Underline=1, Beam=2);
// index by it to recover the app's string union.
const CURSOR_SHAPES: CursorShape[] = ['block', 'underline', 'beam'];

function toCursorState(c: {col: number; row: number; shape: number; visible: boolean}): CursorState {
  return {col: c.col, row: c.row, visible: c.visible, shape: CURSOR_SHAPES[c.shape] ?? 'block'};
}

// Generated records carry `terminalNames` as a JS `Map`; the app reads it as a
// plain `Record`. Convert and pass everything else through.
function toProjectInfo(p: ProjectInfo & {terminalNames: unknown}): ProjectInfo {
  const names = p.terminalNames;
  return {
    ...p,
    terminalNames:
      names instanceof Map ? Object.fromEntries(names) : (names as Record<string, string>),
  };
}

/** Warn once per process, not once per `getOkenaNative()` caller. */
let staleBindingWarned = false;

function warnStaleBinding(): void {
  if (staleBindingWarned) return;
  staleBindingWarned = true;
  console.warn(
    'okena native bindings predate `get_cert_fingerprint`: TLS certificate ' +
      'pins cannot be read, so they are not persisted and saved tokens are ' +
      'reused unpinned. Run `npm run ubrn:android` or `npm run ubrn:ios` to ' +
      'regenerate src/generated. See mobile/rn/README.md.',
  );
}

export function getOkenaNative(): OkenaNative {
  try {
    // The local `okena-mobile-ffi` package entry (src/index.tsx) installs the
    // JSI bindings (`installRustCrate()` + `initialize()`) on first import and
    // re-exports every generated function at the top level. Most functions
    // satisfy `OkenaNative` structurally as-is; the wrapper below only overrides
    // the ones whose enum shapes need translating (see adapters above).
    const gen = require('okena-mobile-ffi');
    const pinsReadable = typeof gen.getCertFingerprint === 'function';
    if (!pinsReadable) warnStaleBinding();
    return {
      ...gen,
      connectionStatus: (connId: ConnId) =>
        toConnectionStatus(gen.connectionStatus(connId)),
      getCursor: (connId: ConnId, terminalId: TerminalId) =>
        toCursorState(gen.getCursor(connId, terminalId)),
      getProjects: (connId: ConnId) =>
        (gen.getProjects(connId) as Array<ProjectInfo & {terminalNames: unknown}>).map(
          toProjectInfo,
        ),
      canReportCertFingerprint: () => pinsReadable,
      getCertFingerprint: (connId: ConnId) =>
        pinsReadable ? gen.getCertFingerprint(connId) : undefined,
    } as OkenaNative;
  } catch (e) {
    throw new Error(
      'okena native module not generated yet — run `npm run ubrn:android` or ' +
        '`npm run ubrn:ios` to cross-compile crates/okena-mobile-ffi and emit ' +
        'src/generated. See mobile/rn/README.md. Underlying error: ' +
        String(e),
    );
  }
}
